### ISSUE TITLE
ModuleNotFoundError: No module named 'memory_profiler'

### ISSUE THREAD

**Issue by luke-e-gibson-1** [IAJWasTooShort/PyCraft#3]
I am getting this ModuleNotFoundError when i run main.py file in powershell and the same in command promt

**To Reproduce**
1. clone The Git Repo
2. Cd in to the folder
3. and run with python mian.py

**Expected behavior**
I expected to see a window appear

**Screenshots**
` pygame 2.0.1 (SDL 2.0.14, Python 3.9.2)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "C:\Users\user\PyCraft\main.py", line 19, in <module>
    from game.entity.Player import Player
  File "C:\Users\user\PyCraft\game\entity\Player.py", line 5, in <module>
    from game.Scene import Scene
  File "C:\Users\user\PyCraft\game\Scene.py", line 1, in <module>
    from game.items.ItemHandler import ItemHandler
  File "C:\Users\user\PyCraft\game\items\ItemHandler.py", line 2, in <module>
    from game.world.worldGenerator import worldGenerator
  File "C:\Users\user\PyCraft\game\world\worldGenerator.py", line 8, in <module>
    from memory_profiler import profile
ModuleNotFoundError: No module named 'memory_profiler'
`

**Desktop (please complete the following information):**
 - OS: Winodws 11
 - Version I do not know what to put here

**Additional context**

**Comment by luke-e-gibson-1** [comment]
I solved it by installing memory-profiler library but a new problem when starting the game a window appears but this and closes with this error
`pyglet.image.ImageException: Image dimensions must be powers of 2 to use mipmaps.`

**Comment by luke-e-gibson-1** [comment]
i have solved both problem

i will close this Issue
